export const GET_PROD_DETAILS_REQUEST = "GET_PROD_DETAILS_REQUEST"
export const GET_PROD_DETAILS_SUCCESS = "GET_PROD_DETAILS_SUCCESS"
export const GET_PROD_DETAILS_FAILURE = "GET_PROD_DETAILS_FAILURE"

export const ADD_CART_ITEMS = "ADD_CART_ITEMS"
export const CLEAR_CART_CHECKOUT = "CLEAR_CART_CHECKOUT"
export const REMOVE_ITEM_FROM_CART = "REMOVE_ITEMS_FROM_CART"