export const GET_PROD_DETAILS_REQUEST = "GET_PROD_DETAILS_REQUEST"
export const GET_PROD_DETAILS_SUCCESS = "GET_PROD_DETAILS_SUCCESS"
export const GET_PROD_DETAILS_FAILURE = "GET_PROD_DETAILS_FAILURE"