export const GET_BOOk_REQUEST = "GET_BOOk_REQUEST"
export const GET_BOOk_SUCCESS = "GET_BOOk_SUCCESS"
export const GET_BOOk_FAILURE = "GET_BOOk_FAILURE"

export const GET_MENS_REQUEST = "GET_MENS_REQUEST"
export const GET_MENS_SUCCESS = "GET_MENS_SUCCESS"
export const GET_MENS_FAILURE = "GET_MENS_FAILURE"

